name: YouTube Auto-Deployer
on:
  push:
    paths:
      - 'VideoClips/**' # Only runs when files are added to this folder

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get install ffmpeg
          pip install -r requirements.txt

      - name: Run Automator Logic
        run: |
          # Count how many mp4 files are in the folder
          COUNT=$(ls VideoClips/*.mp4 | wc -l)
          echo "Found $COUNT files."
          
          if [ "$COUNT" -eq "1" ]; then
            echo "Running Single Video Mode..."
            python youtube_automatorVideo.py ./VideoClips
          elif [ "$COUNT" -ge "5" ]; then
            echo "Running Ranking Mode..."
            python youtube_automator.py ./VideoClips
          else
            echo "Not enough files for a ranking, and more than one file found."
          fi
